### ISSUE TITLE
[BUG] managed_virtual_network_enabled default value is inconsistent with documentation

### ISSUE THREAD

**Issue by jdrago999** [claranet/terraform-azurerm-data-factory#1]
### Community Note

We noticed that https://registry.terraform.io/modules/claranet/data-factory/azurerm/latest shows the attribute `managed_virtual_network_enabled` is not required, and defaults to `true` but the code itself had set the default value to `false`.

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.67.0

### AzureRM Provider Version

3.67.0

### Affected Resource(s)/Data Source(s)

azurerm data factory

### Terraform Configuration Files

```hcl
N/A
```

### Debug Output/Panic Output

```shell
N/A
```

**Comment by BzSpi** [comment]
Hello,

Thanks for opening an issue.
I cannot reproduce the issue and the value and documentation seems consistent for me.
I saw that you have open a PR, but on our CI tfvars file that is unused outside the CI context.

**Comment by jdrago999** [comment]
Here is a screenshot of the documentation here: https://registry.terraform.io/modules/claranet/data-factory/azurerm/latest

<img width="1109" alt="image" src="https://github.com/claranet/terraform-azurerm-data-factory/assets/37591/a8f4366f-70e7-4142-b42d-a28b6c7b1e85">

Here is the actual implementation (in red) and update to make the implementation consistent with the documentation (in green):

<img width="452" alt="image" src="https://github.com/claranet/terraform-azurerm-data-factory/assets/37591/7bde2986-c989-40fc-92da-bd21a7a7363a">

**Comment by BzSpi** [comment]
The `terraform.tfvars.ci` is a file only used in our CI process and do not change the module behavior.
When using the module the `managed_virtual_network_enabled` is set to true by default.
