### ISSUE TITLE
Release v6.1.0 still uses older version of "claranet/diagnostic-settings/azurerm(5.0.0)"

### ISSUE THREAD

**Issue by Kumar9676** [claranet/terraform-azurerm-data-factory#3]
### Community Note

azurerm_monitor_diagnostic_categories

### Terraform Version

1.3.7

### AzureRM Provider Version

3.31.0

### Affected Resource(s)/Data Source(s)

azurerm_monitor_diagnostic_categories

### Terraform Configuration Files

```hcl
module "data_factory_app_01" {
  source  = "claranet/data-factory/azurerm"
  version = "6.1.0"

  location_short = ""
  client_name    = "${var.client_name}-app-01"
  environment    = var.environment
  stack          = var.stack
  name_prefix    = var.region_short_prefix
  use_caf_naming = true

  resource_group_name = module.rg.resource_group_name
  location            = module.azure_region.location

  integration_runtime_type        = "SelfHosted"
  integration_runtime_custom_name = "MartechSDWANWestUSIntegrationRuntime"
  integration_runtime_description = "Integration runtime to enable connectivity to Data Sources outside of Azure Cloud"

  logs_destinations_ids = []
  #logs_retention_days   = 90
}
```

### Debug Output/Panic Output

```shell
Release version 6.1.0 uses older version of "claranet/diagnostic-settings/azurerm(5.0.0)" which uses deprecated attribute for diagnostic settings.

on .terraform/modules/data_factory_app_01.diagnostics/locals.tf line 8, in locals:
│    8:     try(data.azurerm_monitor_diagnostic_categories.main[0].logs, [])
```

### Expected Behaviour

Must be using latest module of claranet/diagnostic-settings/azurerm

### Actual Behaviour

Release version 6.1.0 uses older version of "claranet/diagnostic-settings/azurerm(5.0.0)"

**Comment by BzSpi** [comment]
Hello,

Thank you for letting us know.
Modifications were done but unreleased. You can now use the release [v6.2.0](https://registry.terraform.io/modules/claranet/data-factory/azurerm/6.2.0).
We'll push a new version soon with latest diagnostics version.

**Comment by BzSpi** [comment]
Hello @Kumar9676 

Version [v6.3.0](https://registry.terraform.io/modules/claranet/data-factory/azurerm/6.3.0) has been released with latest diagnostic settings version.

Let us know if you have further remarks.
